### ISSUE TITLE
Hacktober Fest 2020 ✅🔥

### ISSUE THREAD

**Issue by shreyanshchordia** [shreyanshchordia/Binary-Trees#1]
I hereby invite beginners who are looking forward to dive into **Open Source Contribution** this year through _**Hacktober Fest 2020 by Digital Ocean**_ 🔥🔥🔥

This repository is focused especially on Binary Trees.
Lets provide implementation of Binary Trees to the world in every possible language.
You are open to adding new languages.
Focus must be on Quality and not Quantity. Hence clean code, with specific details must be provided.

✅ Fork the repository !!!! 
✅ Add your code !!!! 
✅ Send a Pull Request !!!!

**Comment by Ace117MC** [comment]
can i code for C++

**Comment by shreyanshchordia** [comment]
@Ace117MC go for it! And send in a pull request. Make sure the code is clean and the question is clear as well. And not just the solution.
Try to solve famous BST questions in whatever language you choose. 

All the best!!

**Comment by Jstnlee1997** [comment]
Hi I am a beginner, can I try and code this in JS or Python?

**Comment by shreyanshchordia** [comment]
@Jstnlee1997 go for it !!

**Comment by Mahendra7985** [comment]
i would like to work on this

**Comment by shreyanshchordia** [comment]
@Mahendra7985 fork the repository, contribute and then make a pull request 🔥
