### ISSUE TITLE
Binary Trees | Any Language 🔥

### ISSUE THREAD

**Issue by shreyanshchordia** [shreyanshchordia/Binary-Trees#12]
Check out, how can you contribute to the repository by refering to README.md. This repository is looking for code on Binary Trees in any language that you like. Go for it 🔥🔥🔥🔥

**Comment by js899** [comment]
I'd like to do in python

**Comment by shreyanshchordia** [comment]
@js899 go for it!!

**Comment by js899** [comment]
okay !!

**Comment by ArdhenisAflah** [comment]
i want make with c#

**Comment by shreyanshchordia** [comment]
No issues @sayaPintar go for it!! Add a folder for C# add add your code

**Comment by garimamishraa** [comment]
Can i contribute in c++?

**Comment by shreyanshchordia** [comment]
@garimamishraa go for it!!

**Comment by shreyanshchordia** [comment]
@garimamishraa @js899 @sayaPintar I am more than willing to accept all your contributions. But requesting you to follow the guidelines. Also please put description of the problem in the comments of your code.

**Comment by ArdhenisAflah** [comment]
but i cant make new folder for c#

**Comment by shreyanshchordia** [comment]
@sayaPintar done !!

**Comment by ArdhenisAflah** [comment]
Yap, thanks sir

**Comment by ameya-shahu** [comment]
Can I contribute in Kotlin?

**Comment by shubhamnag14** [comment]
i would to like to this pythob or c

**Comment by js899** [comment]
@shreyanshchordia Plz check once. lowest common ancestor in bt using python. Mention if any edits required.

**Comment by shubhamnag14** [comment]
@shreyanshchordia could you please assign me  this work..i would like to work with python

**Comment by shairanshrawat** [comment]
@shreyanshchordia I'd like to contribute in python or c++ can you assign me

**Comment by alkatrivedi** [comment]
I would like to implement in C. May I?

**Comment by shreyanshchordia** [comment]
@shairanshrawat @alkatrivedi go for it!!

**Comment by amanchhaparia** [comment]
@shreyanshchordia I'd like to contribute in c++ language, 
May l?

**Comment by shreyanshchordia** [comment]
@amanchhaparia sure but C++ folder already has a lot of codes. Make sure that your problem statement is not already present in the folder or else it won't be considered.

**Comment by amanchhaparia** [comment]
> @amanchhaparia sure but C++ folder already has a lot of codes. Make sure that your problem statement is not already present in the folder or else it won't be considered.

Yeah sure, I ll take care tht prob is not repeated

**Comment by gautam-dev-maker** [comment]
@shreyanshchordia I'd like to contribute in dart language,
May I?

**Comment by AmeyaPhadnis-2019H1030012G** [comment]
@shreyanshchordia I would like to contribute in python, I am new to the open-source community and looking forward to opportunities to contribute. Thanks in advance!
