### ISSUE TITLE
✅ NEED DOCUMENTATION FOR THE REPOSITORY 

### ISSUE THREAD

**Issue by shreyanshchordia** [shreyanshchordia/Binary-Trees#2]
- Add Documentation to explain the purpose of the repository i.e. to provide solution to the famous problems on Binary Trees in as many languages as possible.  

- Add a section for beginners to explain how can they contribute to the repository. 

- Hacktober Fest Guidelines

**Comment by akt114** [comment]
I'd like to work on this issue.

**Comment by AyushRajSharma** [comment]
i want to work on this

**Comment by shreyanshchordia** [comment]
@akt114 Assigned you the issue 👍🏻

**Comment by AyushRajSharma** [comment]
@shreyanshchordia please assign me also. i want to work with this

**Comment by vishwas-yogi** [comment]
@shreyanshchordia  Hi! I would like to wok on it. You can assign me task for the same. Thank you.

**Comment by shreyanshchordia** [comment]
@partha-sarathi-yogi @AyushRajSharma @akt114 send me a PR! 

Now there is no assignment. You can go for it. If you wish to!  

Start doing it step by step. I will accept all contributions! 👍🏻🔥
